version: "3.9"

services:
  ros2-dev:
    image: ros2-workshop-amd64:latest
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: ros2_dev
    volumes:
      - .:/home/dev/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    working_dir: /home/dev/workspace
    user: dev
    # network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
    command: sleep infinity
